version: "3.8"

services:
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/html
    links: 
      - database

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - database

  database:
    container_name: ${PROJECT_NAME}_mysql
    build:
      context: ./docker/mysql
    restart: "always"
    ports: 
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: tenis
      MYSQL_USER: docker
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test 
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin
    links: 
      - database
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: test
      MYSQL_USER: docker
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
